language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
env:
  global:
    - RUST_BACKTRACE=1
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - name: cargo fmt
      rust: stable
      script:
        - rustup component add rustfmt
        - cargo fmt

script:
  - cargo build
  - cargo test

notifications:
  email:
    on_success: never
