[package]
name = "urdf-rs"
version = "0.5.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
edition = "2018"
description = "URDF parser using serde-xml-rs"
license = "Apache-2.0"
keywords = ["robotics", "robot", "ros", "urdf"]
categories = ["data-structures", "parsing"]
repository = "https://github.com/openrr/urdf-rs"
documentation = "http://docs.rs/urdf-rs"

[dependencies]
serde-xml-rs = "0.4.0"
serde = "1.0.118"
serde_derive = "1.0.118"
RustyXML = "0.3.0"
regex = "1.4.2"
