name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        rust: [ stable, beta, nightly ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
    - run: cargo fmt -- --check
      if: matrix.rust == 'stable'
    - run: cargo clippy --all-targets
      if: matrix.rust == 'stable'
    - run: cargo build --verbose
    - run: cargo test --verbose
